### ISSUE TITLE
Fix CodeEditor UI issues

### ISSUE THREAD

**Issue by marcgabe15** [edugator-cise/edugator-staff-frontend#115]
**Describe the bug**
- [x] #147
- [x] #148
- [x] #149
- [x] #150
- [x] #151
- [x] #152
- [x] #153
- [x] #154

![image (10)](https://user-images.githubusercontent.com/33824219/142337741-94ecef03-2379-407b-af55-69be52b4013b.png)
![image (9)](https://user-images.githubusercontent.com/33824219/142337745-b8556ba4-de8a-4a8b-b8c0-0b36d5f85c32.png)

**Comment by kapooramanpreet** [comment]
This looks good and all issues are resolved.
