### ISSUE TITLE
Excess whitespace on some pages

### ISSUE THREAD

**Issue by a-penton** [edugator-cise/edugator-staff-frontend#123]
**Description**
On the TwoSum page, there is excess whitespace between where code is written and the input/output/compiler results

**To Reproduce**
1. On edugator.app, click on Modules then Heaps
2. On the left menu, click on Heaps then TwoSum
3. See error on the right

**Expected behavior**
There is less whitespace so the user doesn't have to scroll to see compiler output.

**Screenshots**
![image](https://user-images.githubusercontent.com/57507806/142511028-d663878b-554e-4b7c-9368-74d95cf9334f.png)

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by marcgabe15** [comment]
fixed in @digitdustin 's PR
