### ISSUE TITLE
No newline characters in code ouptut

### ISSUE THREAD

**Issue by a-penton** [edugator-cise/edugator-staff-frontend#124]
**Description**
When code output contains a newline character, it appears as a space instead of a newline.

**To Reproduce**
1. From edugator.app, click on Start Coding.
2. Click on '8. Sets and Maps' then '8.1 Find the Digits: Difference between Shuffled Digits'.
3. In the code box, replace line 6 (the comment) with this:
```
	cout << x << endl << x;
```
4. Click on 'Run Code'.
5. Scroll down to view output. The output does not appear to be separated by a newline.

**Expected behavior**
The output should appear to be on two separate lines.

**Screenshots**
![image](https://user-images.githubusercontent.com/57507806/142512500-2e212998-99fe-46cb-9f27-fd5b5d344b2c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69

**Additional context**
Marc mentioned that it is registering as a newline character, it just isn't showing up properly.

**Comment by marcgabe15** [comment]
@marcgabe15  fixed
