### ISSUE TITLE
Mobile responsiveness of footer text on Homepage

### ISSUE THREAD

**Issue by kapooramanpreet** [edugator-cise/edugator-staff-frontend#180]
**Describe the bug**
The footer text overflows outside the container for mobile devices.

**To Reproduce**
1. Go to https://edugator.app/
2. Scroll down to the footer
3. See error

**Expected behavior**
The text should shrink in size or should stack properly

**Screenshots**
![image](https://user-images.githubusercontent.com/29406643/149827748-daa12d4c-2666-45f2-b24a-e2f76ffab82f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by digitdustin** [comment]
Fixed in #191
