### ISSUE TITLE
Text overflow in compiler output pane

### ISSUE THREAD

**Issue by kapooramanpreet** [edugator-cise/edugator-staff-frontend#184]
**Describe the bug**
The text overflows in compiler output pane if the length of the text is greater than height of the pane.

**To Reproduce**
1. Go to '[Edugator 1.1](https://edugator.app/code/61dc5d16fd23ac28594f53ae)'
2. Write a program to print text on 100 different lines
3. Click on 'Run'
4. Scroll down to 'Compiler output'
5. See error

**Expected behavior**
The inner grey textarea should depend on the length of output

**Screenshots**
![image](https://user-images.githubusercontent.com/29406643/163694149-71744dae-65d8-41b4-8e1c-ba7661df5074.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 100.0.4896.75

**Comment by digitdustin** [comment]
Fixed in #191
