### ISSUE TITLE
Create UI for the Metadata of a new problem

### ISSUE THREAD

**Issue by tanner-ropp** [edugator-cise/edugator-staff-frontend#21]
# User story
As an educator using the admin portal, I want to be able to enter metadata information about a problem

# Acceptance criteria
- [ ] The UI contains form elements for all metadata fields

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by marcgabe15** [comment]
Implemented by Nov 5th
