### ISSUE TITLE
Create UI for the Server Config of a new problem

### ISSUE THREAD

**Issue by tanner-ropp** [edugator-cise/edugator-staff-frontend#24]
# User story
As an educator using the admin portal, I want to have an interface to enter server config information for a problem.

# Acceptance criteria
- [ ] There is a form with all relevant server config fields

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by marcgabe15** [comment]
Implemented by Nov 5th
