### ISSUE TITLE
Create UI for the Test Editor of a new problem

### ISSUE THREAD

**Issue by tanner-ropp** [edugator-cise/edugator-staff-frontend#25]
# User story
As an educator using the admin portal, I want to be able to add and configure new test cases for each problem.

# Acceptance criteria
- [ ] Be able to add new tests with inputs and and expected outputs.

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by marcgabe15** [comment]
Implemented by Nov 5th
