### ISSUE TITLE
Create Redux logic for stepping through the new problem page

### ISSUE THREAD

**Issue by tanner-ropp** [edugator-cise/edugator-staff-frontend#26]
# User story
As an educator I want to have my input confirmed on each stage of the problem page before I continue to the next step.

# Acceptance criteria
- [x] There is logic to prevent the user from stepping forward on the editor until the current page is validated successfully.

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified

**Comment by marcgabe15** [comment]
Implemented by Nov 5th
