### ISSUE TITLE
Link Test Editor form to redux 

### ISSUE THREAD

**Issue by tanner-ropp** [edugator-cise/edugator-staff-frontend#33]
# User story
As an educator I want to be able to package my form content in the app state for later submission.

Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.

# Acceptance criteria
- [ ] All fields in the tests editor form get stored in redux before moving to the next section

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by marcgabe15** [comment]
Implemented by Nov 5th
