### ISSUE TITLE
Ability to add header and footer

### ISSUE THREAD

**Issue by tanner-ropp** [edugator-cise/edugator-staff-frontend#38]
# User story
As an educator I want to be able to add header and footer in the code editor

# Acceptance criteria
- [ ] There are fields to add headers and footers in the code editor

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by marcgabe15** [comment]
Implemented by Nov 5th
