### ISSUE TITLE
Create Module Page list

### ISSUE THREAD

**Issue by marcgabe15** [edugator-cise/edugator-staff-frontend#4]
# Create Module list
As an edugator staff user, I want to able to see the list of modules and problems

# Acceptance criteria
- [x] Accessible
- [x] Lists all problems and modules
- [x] Fits to multiple screen sizes

**Comment by AqSlz** [comment]
Existing Modules and Problems are visible, next issue is for adding, deleting, and renaming of modules.

Currently adding new modules works, but I will next do these features through redux.
