### ISSUE TITLE
Ability to add template files to problems

### ISSUE THREAD

**Issue by tanner-ropp** [edugator-cise/edugator-staff-frontend#44]
# User story
As an educator, I want to be able to add templates to problems for students to download

# Acceptance criteria
- [ ] There is a field to add a link for a template file.

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by marcgabe15** [comment]
Implemented by Nov 5th
