### ISSUE TITLE
Ability to toggle the visibility of I/O for test cases

### ISSUE THREAD

**Issue by tanner-ropp** [edugator-cise/edugator-staff-frontend#45]
# User story
As an educator I want to be able to toggle the visibility of test case input and output for each test in a problem

# Acceptance criteria
- [ ] There is a visibility field for each input and output of all the test cases

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by marcgabe15** [comment]
Implemented by Nov 5th
