### ISSUE TITLE
No way to clear alerts

### ISSUE THREAD

**Issue by joshuadargan** [edugator-cise/edugator-staff-frontend#86]
**Describe the bug**
Alerts can persist at the bottom of the screen for a while and block interaction.

**To Reproduce**
1. Go to Modules
2. Perform some action
3. Scroll down to the bottom
4. See error where the alert can block interaction

**Expected behavior**
Allow alerts to be dismissable

**Screenshots**
![image](https://user-images.githubusercontent.com/40403340/140574577-bf0b4f70-506b-475e-a1e6-1adc72dc6f4d.png)

**Comment by AqSlz** [comment]
That previous PR solved a bug of the alert being shown again. But it does not allow users to dismiss alerts. A future PR will address this.

**Comment by AqSlz** [comment]
Also linking a PR to make the alerts from the Accounts page dismissable
