### ISSUE TITLE
Template package can be a non-valid uri

### ISSUE THREAD

**Issue by joshuadargan** [edugator-cise/edugator-staff-frontend#88]
**Describe the bug**
Template package can be a non-valid uri

**To Reproduce**
1. Go to 'edit a problem'
2. Go to template package
3. enter "http://www..com"

**Expected behavior**
should reject an invalid uri

**Screenshots**
![image](https://user-images.githubusercontent.com/40403340/140576805-a8621343-fe3c-4b21-a6cf-d9cc5935b3ab.png)

**Comment by tanner-ropp** [comment]
So it turns out http://www..com is a valid uri, and more specifically joi (the validation used in the back-end) accepts it
